name: build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate tag 
        run: |
          DATETAG=$(date +"%Y.%m.%d")
          FULL_TAG="jryberg/myuplink_prometheus_exporter:$DATETAG-$GITHUB_RUN_NUMBER"
          FULL_LATEST_TAG="jryberg/myuplink_prometheus_exporter:latest"
          echo "full-tag=$FULL_TAG" >> $GITHUB_OUTPUT
          echo "full-latest-tag=$FULL_LATEST_TAG" >> $GITHUB_OUTPUT
        id: tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push new container
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tag.outputs.full-tag }},${{ steps.tag.outputs.full-latest-tag }}
